SELECT * FROM Customers
WHERE Country = 'Mexico';
SELECT * FROM Customers
WHERE Country <> 'Mexico';
SELECT * FROM Suppliers
WHERE Country != 'USA';
SELECT * FROM Products
WHERE Price > 90.00;
SELECT * FROM Products
WHERE ProductName > 'U'
