CREATE TABLE MyTable13(
col1 INT, col2 INT
);

ALTER TABLE MyTable13 ADD COLUMN col3 VARCHAR(10);
DESC MyTable13;

ALTER TABLE MyTable13 ADD COLUMN col4 DEC(10, 2);

ALTER TABLE MyTable13 ADD COLUMN col5 INT;
ALTER TABLE MyTable13 ADD COLUMN col6 INT FIRST;
ALTER TABLE MyTable13 ADD COLUMN col7 INT FIRST;

ALTER TABLE MyTable13 ADD COLUMN col8 VARCHAR(9) AFTER col7;

ALTER TABLE MyTable13 ADD COLUMN col9 INT FIRST;

ALTER TABLE MyTable13 ADD COLUMN col10 DEC(5,2) AFTER col6;