DESC MyTable13;
ALTER TABLE MyTable13
MODIFY COLUMN col20 VARCHAR(40);

SELECT * FROM MyTable13;

ALTER TABLE MyTable13
MODIFY COLUMN col13 VARCHAR(3);

ALTER TABLE MyTable13
MODIFY COLUMN col7 DEC(5,3);

ALTER TABLE MyTable13
MODIFY COLUMN col8 VARCHAR(9) FIRST;

ALTER TABLE MyTable13
MODIFY COLUMN col9 DEC(6,2) AFTER col20;