CREATE TABLE MyTable17(
Col1 INT, Col2 INT NOT NULL
);

INSERT INTO MyTable17 (Col1, Col2)
VALUES (100, 200);
INSERT INTO MyTable17 (Col2)
VALUES (200);
INSERT INTO MyTable17 (Col1)
VALUES (100);

SELECT * FROM MyTable17;

CREATE TABLE MyTable18(
Col1 VARCHAR(20), Col2 VARCHAR(20) NOT NULL
);
INSERT INTO MyTable18 (Col1, Col2)
VALUES ('qwdqwd', 'abcdef');
INSERT INTO MyTable18 (Col1)
VALUES ('qwdqwd');
INSERT INTO MyTable18 (Col2)
VALUES ( 'abcdef');
SELECT * FROM MyTable18;

DESC MyTable17;

CREATE TABLE MyTable19(
Col1 INT DEFAULT 0, Col2 INT NOT NULL
);

DESC MyTable19;
INSERT INTO MyTable19 (Col2)
VALUES (200);
SELECT * FROM MyTable19;

CREATE TABLE MyTable20(
Col1 INT, Col2 INT NOT NULL, Col3 INT DEFAULT 0, Col4 INT NOT NULL DEFAULT 0
);
DESC MyTable20;