CREATE TABLE MyTable24(
COl1 INT PRIMARY KEY
);
DESC MyTable25;

CREATE TABLE MyTable25(
Col1 INT, PRIMARY KEY (Col1)
);

CREATE TABLE MyTable26(
Col1 INT, Col2 INT, PRIMARY KEY (Col1, Col2)
);
DESC MyTable26;	
INSERT INTO MyTable26 (Col1, Col2)
VALUES ( 1, 1);
INSERT INTO MyTable26 (Col1, Col2)
VALUES ( 2, 2);
INSERT INTO MyTable26 (Col1, Col2)
VALUES ( 1, 2);
INSERT INTO MyTable26 (Col1, Col2)
VALUES ( 1, 1);
SELECT * FROM MyTable26;

CREATE TABLE MyTable27(
Col1 INT, Col2 INT, PRIMARY KEY (Col1), PRIMARY KEY (Col2)
);

DESC MyTable26;