CREATE TABLE MyTable28(
Col1 INT, Col2 INT, Col3 INT , Col4 INT
);
ALTER TABLE MyTable28
MODIFY COLUMN Col1 INT DEFAULT 10;

ALTER TABLE MyTable28
MODIFY COLUMN Col2 INT NOT NULL;

ALTER TABLE MyTable28
MODIFY COLUMN Col3 INT DEFAULT 0;

ALTER TABLE MyTable28
MODIFY COLUMN Col4 INT PRIMARY KEY DEFAULT 100;

DESC MyTable28;

CREATE TABLE MyTable29(
Col1 INT, Col2 INT, Col3 INT , Col4 INT
);

ALTER TABLE MyTable29
ADD PRIMARY KEY (Col1, Col2);
DESC MyTable29;